// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <demo.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __HSFoward__HSBnsProc__amdfun_name = "amdfun";

static const ::std::string __HSFoward__HSBnsProc__fun_name = "fun";

::Ice::Object* IceInternal::upCast(::HSFoward::HSBnsProc* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::HSFoward::HSBnsProc* p) { return p; }

void
HSFoward::__read(::IceInternal::BasicStream* __is, ::HSFoward::HSBnsProcPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::HSFoward::HSBnsProc;
        v->__copyFrom(proxy);
    }
}

IceAsync::HSFoward::AMD_HSBnsProc_amdfun::AMD_HSBnsProc_amdfun(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::HSFoward::AMD_HSBnsProc_amdfun::ice_response(const ::std::string& __ret)
{
    if(__validateResponse(true))
    {
        try
        {
            ::IceInternal::BasicStream* __os = this->__os();
            __os->write(__ret);
        }
        catch(const ::Ice::Exception& __ex)
        {
            __exception(__ex);
            return;
        }
        __response(true);
    }
}

::std::string
IceProxy::HSFoward::HSBnsProc::amdfun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__HSFoward__HSBnsProc__amdfun_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::HSFoward::HSBnsProc* __del = dynamic_cast< ::IceDelegate::HSFoward::HSBnsProc*>(__delBase.get());
            return __del->amdfun(num, str, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::HSFoward::HSBnsProc::begin_amdfun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__HSFoward__HSBnsProc__amdfun_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __HSFoward__HSBnsProc__amdfun_name, __del, __cookie);
    try
    {
        __result->__prepare(__HSFoward__HSBnsProc__amdfun_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(num);
        __os->write(str);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::HSFoward::HSBnsProc::end_amdfun(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __HSFoward__HSBnsProc__amdfun_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

::Ice::Int
IceProxy::HSFoward::HSBnsProc::fun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__HSFoward__HSBnsProc__fun_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::HSFoward::HSBnsProc* __del = dynamic_cast< ::IceDelegate::HSFoward::HSBnsProc*>(__delBase.get());
            return __del->fun(num, str, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::HSFoward::HSBnsProc::begin_fun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__HSFoward__HSBnsProc__fun_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __HSFoward__HSBnsProc__fun_name, __del, __cookie);
    try
    {
        __result->__prepare(__HSFoward__HSBnsProc__fun_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(num);
        __os->write(str);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::HSFoward::HSBnsProc::end_fun(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __HSFoward__HSBnsProc__fun_name);
    ::Ice::Int __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::HSFoward::HSBnsProc::ice_staticId()
{
    return ::HSFoward::HSBnsProc::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::HSFoward::HSBnsProc::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::HSFoward::HSBnsProc);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::HSFoward::HSBnsProc::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::HSFoward::HSBnsProc);
}

::IceProxy::Ice::Object*
IceProxy::HSFoward::HSBnsProc::__newInstance() const
{
    return new HSBnsProc;
}

::std::string
IceDelegateM::HSFoward::HSBnsProc::amdfun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __HSFoward__HSBnsProc__amdfun_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(num);
        __os->write(str);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::HSFoward::HSBnsProc::fun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __HSFoward__HSBnsProc__fun_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(num);
        __os->write(str);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::HSFoward::HSBnsProc::amdfun(::Ice::Int, const ::std::string&, const ::Ice::Context*)
{
    throw ::Ice::CollocationOptimizationException(__FILE__, __LINE__);
    return ::std::string(); // to avoid a warning with some compilers;
}

::Ice::Int
IceDelegateD::HSFoward::HSBnsProc::fun(::Ice::Int num, const ::std::string& str, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, ::Ice::Int num, const ::std::string& str, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_num(num),
            _m_str(str)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::HSFoward::HSBnsProc* servant = dynamic_cast< ::HSFoward::HSBnsProc*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->fun(_m_num, _m_str, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        ::Ice::Int _m_num;
        const ::std::string& _m_str;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __HSFoward__HSBnsProc__fun_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, num, str, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
HSFoward::HSBnsProc::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __HSFoward__HSBnsProc_ids[2] =
{
    "::HSFoward::HSBnsProc",
    "::Ice::Object"
};

bool
HSFoward::HSBnsProc::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__HSFoward__HSBnsProc_ids, __HSFoward__HSBnsProc_ids + 2, _s);
}

::std::vector< ::std::string>
HSFoward::HSBnsProc::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__HSFoward__HSBnsProc_ids[0], &__HSFoward__HSBnsProc_ids[2]);
}

const ::std::string&
HSFoward::HSBnsProc::ice_id(const ::Ice::Current&) const
{
    return __HSFoward__HSBnsProc_ids[0];
}

const ::std::string&
HSFoward::HSBnsProc::ice_staticId()
{
    return __HSFoward__HSBnsProc_ids[0];
}

::Ice::DispatchStatus
HSFoward::HSBnsProc::___amdfun(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Ice::Int num;
    ::std::string str;
    __is->read(num);
    __is->read(str);
    __is->endReadEncaps();
    ::HSFoward::AMD_HSBnsProc_amdfunPtr __cb = new IceAsync::HSFoward::AMD_HSBnsProc_amdfun(__inS);
    try
    {
        amdfun_async(__cb, num, str, __current);
    }
    catch(const ::std::exception& __ex)
    {
        __cb->ice_exception(__ex);
    }
    catch(...)
    {
        __cb->ice_exception();
    }
    return ::Ice::DispatchAsync;
}

::Ice::DispatchStatus
HSFoward::HSBnsProc::___fun(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Ice::Int num;
    ::std::string str;
    __is->read(num);
    __is->read(str);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::Ice::Int __ret = fun(num, str, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __HSFoward__HSBnsProc_all[] =
{
    "amdfun",
    "fun",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
HSFoward::HSBnsProc::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__HSFoward__HSBnsProc_all, __HSFoward__HSBnsProc_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __HSFoward__HSBnsProc_all)
    {
        case 0:
        {
            return ___amdfun(in, current);
        }
        case 1:
        {
            return ___fun(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
HSFoward::HSBnsProc::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
HSFoward::HSBnsProc::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
HSFoward::HSBnsProc::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type HSFoward::HSBnsProc was not generated with stream support";
    throw ex;
}

void
HSFoward::HSBnsProc::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type HSFoward::HSBnsProc was not generated with stream support";
    throw ex;
}
#endif

void 
HSFoward::__patch__HSBnsProcPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::HSFoward::HSBnsProcPtr* p = static_cast< ::HSFoward::HSBnsProcPtr*>(__addr);
    assert(p);
    *p = ::HSFoward::HSBnsProcPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::HSFoward::HSBnsProc::ice_staticId(), v->ice_id());
    }
}
