// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ProxySvr.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ProxySvr.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __HSPW__ProxySvr__Procedure_name = "Procedure";

::Ice::Object* IceInternal::upCast(::HSPW::ProxySvr* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::HSPW::ProxySvr* p) { return p; }

void
HSPW::__read(::IceInternal::BasicStream* __is, ::HSPW::ProxySvrPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::HSPW::ProxySvr;
        v->__copyFrom(proxy);
    }
}

void
HSPW::TagProxySvr::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(cmd);
    __os->write(serial);
    __os->write(status);
    __os->write(data);
}

void
HSPW::TagProxySvr::__read(::IceInternal::BasicStream* __is)
{
    __is->read(cmd);
    __is->read(serial);
    __is->read(status);
    __is->read(data);
}

bool
IceProxy::HSPW::ProxySvr::Procedure(const ::HSPW::TagProxySvr& tagIn, ::HSPW::TagProxySvr& tagOut, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__HSPW__ProxySvr__Procedure_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::HSPW::ProxySvr* __del = dynamic_cast< ::IceDelegate::HSPW::ProxySvr*>(__delBase.get());
            return __del->Procedure(tagIn, tagOut, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::HSPW::ProxySvr::begin_Procedure(const ::HSPW::TagProxySvr& tagIn, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__HSPW__ProxySvr__Procedure_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __HSPW__ProxySvr__Procedure_name, __del, __cookie);
    try
    {
        __result->__prepare(__HSPW__ProxySvr__Procedure_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        tagIn.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::HSPW::ProxySvr::end_Procedure(::HSPW::TagProxySvr& tagOut, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __HSPW__ProxySvr__Procedure_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    tagOut.__read(__is);
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::HSPW::ProxySvr::ice_staticId()
{
    return ::HSPW::ProxySvr::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::HSPW::ProxySvr::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::HSPW::ProxySvr);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::HSPW::ProxySvr::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::HSPW::ProxySvr);
}

::IceProxy::Ice::Object*
IceProxy::HSPW::ProxySvr::__newInstance() const
{
    return new ProxySvr;
}

bool
IceDelegateM::HSPW::ProxySvr::Procedure(const ::HSPW::TagProxySvr& tagIn, ::HSPW::TagProxySvr& tagOut, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __HSPW__ProxySvr__Procedure_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        tagIn.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        tagOut.__read(__is);
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::HSPW::ProxySvr::Procedure(const ::HSPW::TagProxySvr& tagIn, ::HSPW::TagProxySvr& tagOut, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::HSPW::TagProxySvr& tagIn, ::HSPW::TagProxySvr& tagOut, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_tagIn(tagIn),
            _m_tagOut(tagOut)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::HSPW::ProxySvr* servant = dynamic_cast< ::HSPW::ProxySvr*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->Procedure(_m_tagIn, _m_tagOut, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::HSPW::TagProxySvr& _m_tagIn;
        ::HSPW::TagProxySvr& _m_tagOut;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __HSPW__ProxySvr__Procedure_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, tagIn, tagOut, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
HSPW::ProxySvr::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __HSPW__ProxySvr_ids[2] =
{
    "::HSPW::ProxySvr",
    "::Ice::Object"
};

bool
HSPW::ProxySvr::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__HSPW__ProxySvr_ids, __HSPW__ProxySvr_ids + 2, _s);
}

::std::vector< ::std::string>
HSPW::ProxySvr::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__HSPW__ProxySvr_ids[0], &__HSPW__ProxySvr_ids[2]);
}

const ::std::string&
HSPW::ProxySvr::ice_id(const ::Ice::Current&) const
{
    return __HSPW__ProxySvr_ids[0];
}

const ::std::string&
HSPW::ProxySvr::ice_staticId()
{
    return __HSPW__ProxySvr_ids[0];
}

::Ice::DispatchStatus
HSPW::ProxySvr::___Procedure(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::HSPW::TagProxySvr tagIn;
    tagIn.__read(__is);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::HSPW::TagProxySvr tagOut;
    bool __ret = Procedure(tagIn, tagOut, __current);
    tagOut.__write(__os);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __HSPW__ProxySvr_all[] =
{
    "Procedure",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
HSPW::ProxySvr::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__HSPW__ProxySvr_all, __HSPW__ProxySvr_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __HSPW__ProxySvr_all)
    {
        case 0:
        {
            return ___Procedure(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
HSPW::ProxySvr::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
HSPW::ProxySvr::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
HSPW::ProxySvr::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type HSPW::ProxySvr was not generated with stream support";
    throw ex;
}

void
HSPW::ProxySvr::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type HSPW::ProxySvr was not generated with stream support";
    throw ex;
}
#endif

void 
HSPW::__patch__ProxySvrPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::HSPW::ProxySvrPtr* p = static_cast< ::HSPW::ProxySvrPtr*>(__addr);
    assert(p);
    *p = ::HSPW::ProxySvrPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::HSPW::ProxySvr::ice_staticId(), v->ice_id());
    }
}
